
services:
  app:
    build: .
    image: bavuga-app:latest
    container_name: bavuga-app
    restart: unless-stopped
    ports:
      - "2500:2500"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
      - MONGODB_URI=mongodb://database:27017
      - DATABASE_NAME=language_app
    volumes:
      - ./google-credentials.json:/app/google-credentials.json:ro
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: bavuga-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mongo-data:
